apiVersion: v1
kind: Service
metadata:
  name: {{ include "dev.fullname" . }}
  labels:
{{ include "dev.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 88
      targetPort: 88
      protocol: TCP
      name: swoole
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "dev.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
